plugins:
  # Name could be anything, this name is what appears on the beginning of operation
  # mappings.
  gcp_plugin:
    # Could be 'central_deployment_agent' or 'host_agent'.
    # If 'central_deployment_agent', this plugin will be executed on the
    # deployment dedicated agent, other wise it will be executed on the host agent.
    executor: central_deployment_agent

    # URL to archive containing the plugin or name of directory containing
    # the plugin if it is included in the the blueprint directory under the
    # "plugins" directory.
    source: https://github.com/szpotona/cloudify-gcp-plugin/archive/use_resources.zip

node_types:
  cloudify.gcp.nodes.Instance:
    derived_from: cloudify.nodes.Compute
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          implementation: gcp_plugin.plugin.tasks.create_instance
          inputs:
            gcp_config:
              default: {}
            instance:
              default: {}
        stop:
          implementation: gcp_plugin.plugin.tasks.delete_instance
          inputs:
            gcp_config:
              default: {}

  cloudify.gcp.nodes.Network:
    derived_from: cloudify.nodes.Network
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: gcp_plugin.plugin.tasks.create_network
          inputs:
            gcp_config:
              default: {}
            network:
              default: {}
        delete:
          implementation: gcp_plugin.plugin.tasks.delete_network
          inputs:
            gcp_config:
              default: {}

  cloudify.gcp.nodes.FirewallRule:
    derived_from: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: gcp_plugin.plugin.tasks.create_firewall_rule
          inputs:
            gcp_config:
              default: {}
            firewall_rule:
              default: {}
        delete:
          implementation: gcp_plugin.plugin.tasks.delete_firewall_rule
          inputs:
            gcp_config:
              default: {}
            firewall_rule:
              default: {}

  cloudify.gcp.nodes.SecurityGroup:
    derived_from: cloudify.nodes.SecurityGroup
    interfaces:
      cloudify.interfaces.lifecycle:
        create: 
          implementation: gcp_plugin.plugin.tasks.create_security_group
          inputs: 
            gcp_config:
              description: >
                A dictionary of values to pass to authenticate with the Google Cloud Platform API.
              default: {}
            rules:
              description: >
                You need to pass in either source_tags list OR cidr_ip list,
                and then the following two: ip_protocol and port list OR target_tags list.
              default: []
        delete:          
          implementation: gcp_plugin.plugin.tasks.delete_firewall_rule
          inputs:
            gcp_config:
              description: >
                A dictionary of values to pass to authenticate with the Google Cloud Platform API.
              default: {}

relationships:
  cloudify.gcp.relationships.connected_to:
    derived_from: cloudify.relationships.connected_to

  cloudify.gcp.relationships.contained_in:
    derived_from: cloudify.relationships.contained_in

