version: 2.1

unittest-post-steps: &unittest-post-steps
  post-steps:
    - store_test_results:
        path: /home/circleci/project/nosetests.xml
    - store_artifacts:
        path: /home/circleci/project/coverage.xml
        prefix: tests
    - slack/notify_failed

orbs:
  slack: cloudify/notify-slack@2
  node: cloudify/public-unittest-orb@volatile
  wagonorb: cloudify/wagon-bulder-orb@volatile
  releaseorb: cloudify/release-orb@volatile
  managerorb: cloudify/manager-orb@volatile

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

executors:
  py36:
    docker:
      - image: circleci/python:3.6

  cloudify-machine-py3:
    machine:
       image: ubuntu-2004:202201-02

commands:
  prepare_test_manager:
    steps:
      - run: ecosystem-test prepare-test-manager -l $TEST_LICENSE -es gcp_credentials=$gcp_credentials -s region=us-east1 -s zone=us-east1-b -es ssl_cert=$ssl_cert -es ssl_key=$ssl_key --yum-package python-netaddr --yum-package git  -p $(find ~/project/workspace/build/ -name *centos-Core*x86_64.wgn)  ~/project/plugin.yaml
      - run: ecosystem-test upload-plugin -PN utilities
      - run: ecosystem-test upload-plugin -PN ansible
      - run: ecosystem-test upload-plugin -PN kubernetes

  run_virtual_machine_test:
    steps:
      - run: ecosystem-test local-blueprint-test  -b examples/blueprint-examples/virtual-machine/gcp.yaml --test-id=virtual-machine --on-failure=uninstall-force --timeout=1800 | tee -a run_virtual_machine_test.log
      - store_artifacts:
          path: run_virtual_machine_test.log
      - slack/notify_failed

  run_gke_test:
    steps:
      - run: ecosystem-test local-blueprint-test  -b examples/blueprint-examples/kubernetes/gcp-gke/blueprint.yaml --test-id=gcp-gke  -i resource_prefix=gcpresource-$CIRCLE_BUILD_NUM --on-failure=uninstall-force --timeout=3000 | tee -a run_gke_test.log
      - store_artifacts:
          path: run_gke_test.log
      - slack/notify_failed

  # test blueprints
  run_attach_disk_test:
     steps:
        - run: ecosystem-test local-blueprint-test  -b blueprints/attach-disk.yaml --test-id=gcp-attach-disk  -i zone=europe-west1-b -i region=europe-west1 -i prefix=gcp-attach-disk-test-$CIRCLE_BUILD_NUM --on-failure=uninstall-force --timeout=3000 | tee -a run_attach_disk_test.log
        - store_artifacts:
            path: run_attach_disk_test.log
        - slack/notify_failed

  run_container_engine_test:
    steps:
      - run: ecosystem-test local-blueprint-test  -b blueprints/container-engine.yaml --test-id=gcp-container-engine -i prefix=gcp-container-engine-test-$CIRCLE_BUILD_NUM --on-failure=uninstall-force --timeout=3000 | tee -a run_container_engine_test.log
      - store_artifacts:
          path: run_container_engine_test.log
      - slack/notify_failed

  run_http_balancer_test:
    steps:
      - run: ecosystem-test local-blueprint-test  -b blueprints/http-balancer.yaml --test-id=gcp-http-balancer -i prefix=gcp-http-balancer-test-$CIRCLE_BUILD_NUM --on-failure=uninstall-force --timeout=3000 | tee -a run_http_balancer_test.log
      - store_artifacts:
          path: run_http_balancer_test.log
      - slack/notify_failed

  run_https_balancer_test:
    steps:
      - run: ecosystem-test local-blueprint-test  -b blueprints/https-balancer.yaml --test-id=gcp-https-balancer -i prefix=gcp-https-balancer-test-$CIRCLE_BUILD_NUM --on-failure=uninstall-force --timeout=3000 | tee -a run_https_balancer_test.log
      - store_artifacts:
          path: run_https_balancer_test.log
      - slack/notify_failed

  run_ssl_balancer_test:
    steps:
      - run: ecosystem-test local-blueprint-test  -b blueprints/ssl-balancer.yaml --test-id=gcp-ssl-balancer -i prefix=gcp-ssl-balancer-test-$CIRCLE_BUILD_NUM --on-failure=uninstall-force --timeout=3000 | tee -a run_ssl_balancer_test.log
      - store_artifacts:
          path: run_ssl_balancer_test.log
      - slack/notify_failed

  run_tcp_balancer_test:
    steps:
      - run: ecosystem-test local-blueprint-test  -b blueprints/tcp-balancer.yaml --test-id=gcp-tcp-balancer -i prefix=gcp-tcp-balancer-test-$CIRCLE_BUILD_NUM --on-failure=uninstall-force --timeout=3000 | tee -a run_tcp_balancer_test.log
      - store_artifacts:
          path: run_tcp_balancer_test.log
      - slack/notify_failed

  run_gcp_example_network_test:
    steps:
      - run: ecosystem-test local-blueprint-test  -b examples/blueprint-examples/gcp-example-network/blueprint.yaml --test-id=gcp-example-network-test  -i resource_prefix=gcp-example-network-test-$CIRCLE_BUILD_NUM --on-failure=uninstall-force --timeout=3000 | tee -a run_gcp_example_network_test.log
      - store_artifacts:
          path: run_gcp_example_network_test.log
      - slack/notify_failed
  # cloudify-community/blueprint-examples/gcp-example-network/blueprint.yaml

jobs:
  virtual_machine_integration_tests_py3:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - prepare_test_manager
      - run_virtual_machine_test

  gke_integration_tests_py3:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - prepare_test_manager
      - run_gke_test

  attach_disk_and_container_engine_test_py3:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - prepare_test_manager
      - run_attach_disk_test
      - run_container_engine_test

  http_balancer_and_https_balancer_test_py3:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - prepare_test_manager
      - run_http_balancer_test
      - run_https_balancer_test

  ssl_balancer_and_tcp_balancer_test_py3:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - prepare_test_manager
      - run_ssl_balancer_test
      - run_tcp_balancer_test

  gcp_example_network_test_py3:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - prepare_test_manager
      - run_gcp_example_network_test

workflows:
  version: 2.1
  tests:
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job:
          context: 
            - slack-secrets
          <<: *unittest-post-steps
      - node/validate_version_job
      - node/validate_documentation_job
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/

      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/

      - virtual_machine_integration_tests_py3:
          requires:
            - wagonorb/wagon
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - gke_integration_tests_py3:
          requires:
            - wagonorb/wagon
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - releaseorb/release:
          filters:
            branches:
              only: /master/
          requires:
            - node/unittests_job
            - wagonorb/arch64_wagon
            - wagonorb/wagon
            - wagonorb/rhel_wagon
            - virtual_machine_integration_tests_py3
            - gke_integration_tests_py3
      - releaseorb/merge_docs_job:
          filters:
            branches:
              only: /master/
          requires:
            - releaseorb/release
            - node/validate_documentation_job

  nightly:
    triggers:
    - schedule:
        cron: "0 1 * * 0,2,4,6"
        filters:
          branches:
            only:
              - master
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job:
          context: 
            - slack-secrets
          <<: *unittest-post-steps
      - node/validate_version_job
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/

      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/

      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/

      - virtual_machine_integration_tests_py3:
          requires:
            - wagonorb/wagon
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
      - virtual_machine_integration_tests_py3:
          context: 
            - slack-secrets
          requires:
            - wagonorb/build_bundle
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - gke_integration_tests_py3:
          context: 
            - slack-secrets
          requires:
            - wagonorb/wagon
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/

  run_test_only_on_sunday:
      triggers:
      - schedule:
          cron: "0 3 * * 0"
          filters:
            branches:
              only:
                - master
      jobs:
        - node/check_py3_compat_job
        - node/unittests_job:
            context: 
              - slack-secrets
            <<: *unittest-post-steps
        - node/validate_version_job
        - wagonorb/rhel_wagon:
            filters:
              branches:
                only: /([0-9\.]*\-build|master|dev)/
        - wagonorb/wagon:
            filters:
              branches:
                only: /([0-9\.]*\-build|master|dev)/
        - wagonorb/arch64_wagon:
            filters:
              branches:
                only: /([0-9\.]*\-build|master|dev)/
        - attach_disk_and_container_engine_test_py3:
            context: 
            - slack-secrets
            requires:
              - wagonorb/wagon
              - wagonorb/rhel_wagon
              - wagonorb/arch64_wagon
            filters:
              branches:
                only: /([0-9\.]*\-build|master|dev)/


  run_test_only_on_monday:
    triggers:
      - schedule:
          cron: "0 3 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job:
          context: 
            - slack-secrets
          <<: *unittest-post-steps
      - node/validate_version_job
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - http_balancer_and_https_balancer_test_py3:
          context: 
            - slack-secrets
          requires:
            - wagonorb/wagon
            - wagonorb/rhel_wagon
            - wagonorb/arch64_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/


  run_test_only_on_tuesday:
    triggers:
      - schedule:
          cron: "0 3 * * 2"
          filters:
            branches:
              only:
                - master
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job:
          context: 
            - slack-secrets
          <<: *unittest-post-steps
      - node/validate_version_job
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - ssl_balancer_and_tcp_balancer_test_py3:
          context: 
            - slack-secrets
          requires:
            - wagonorb/wagon
            - wagonorb/rhel_wagon
            - wagonorb/arch64_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/


  run_test_only_on_wednesday:
    triggers:
      - schedule:
          cron: "0 3 * * 3"
          filters:
            branches:
              only:
                - master
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job:
          context: 
            - slack-secrets
          <<: *unittest-post-steps
      - node/validate_version_job
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - gcp_example_network_test_py3:
          context: 
            - slack-secrets
          requires:
            - wagonorb/wagon
            - wagonorb/rhel_wagon
            - wagonorb/arch64_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
