version: 2.1

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

executors:
  py27:
    docker:
      - image: circleci/python:2.7

  py36:
    docker:
      - image: circleci/python:3.6

  wagon_generator:
    machine:
      image: ubuntu-1604:201903-01

  cloudify-machine:
    machine:
      image: ubuntu-1604:201903-01

  cloudify-machine-py3:
    machine:
      image: ubuntu-1604:201903-01

commands:


  validate_documentation:
    steps:
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote --recursive
      - run:
          name: Download pip
          command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
      - run:
          name: Install pip
          command: sudo python get-pip.py
      - run:
          name: Install virtualenv
          command: pip install --user virtualenv
      - run:
          name: Init virtualenv
          command: virtualenv env
      - run:
          name: install tox
          command: pip install --user pygithub pyyaml==3.10
      - run:
          name: upgrade setuptools
          command: pip install --upgrade setuptools
      - run:
          name: install local project
          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip
      - attach_workspace:
          at: workspace
      - run: python .circleci/validate_docs.py

  validate_version:
    steps:
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote --recursive
      - run:
          name: Download pip
          command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
      - run:
          name: Install pip
          command: sudo python get-pip.py
      - run:
          name: Install virtualenv
          command: pip install --user virtualenv
      - run:
          name: Init virtualenv
          command: virtualenv env
      - run:
          name: install tox
          command: pip install --user pygithub pyyaml==3.10
      - run:
          name: upgrade setuptools
          command: pip install --upgrade setuptools
      - run:
          name: install local project
          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip
      - attach_workspace:
          at: workspace
      - run: python .circleci/validate_version.py

  run_unittest_py27:
    steps:
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote --recursive
      - run:
          name: install tox
          command: pip install --user tox
      - run:
          name: Run Flake8
          command: /home/circleci/.local/bin/tox -e flake8
      - run:
          name: run unitests with py27
          command: /home/circleci/.local/bin/tox -e py27

  run_unittest_py36:
    steps:
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote --recursive
      - run:
          name: install tox
          command: pip install --user tox
      - run:
          name: Run Flake8
          command: /home/circleci/.local/bin/tox -e flake8
      - run:
          name: run unitests with py36
          command: /home/circleci/.local/bin/tox -e py36

  check_py3_compat:
    steps:
      - run:
          name: install futurize
          command: pip install future --user
      - run:
          # those modules contain code that futurize would want to change,
          # so let's just remove them so that it doesn't report on them
          # (there's no "exclude" functionality in futurize)
          name: remove compat modules
          command: |
            rm cloudify_gcp/_compat.py
      - run:
          name: find python3-incompatible code
          command: |
            FUTURIZE="futurize ."
            while read line; do
              [[ "$line" =~ ^#.* ]] && continue
              FUTURIZE="${FUTURIZE} ${line}"
            done<.circleci/py3fixers
            echo "Running: $FUTURIZE"
            $FUTURIZE>futurize_diffs
      - run:
          name: check that there is no python3-incompatible code
          command: |
            if [[ -s futurize_diffs ]]; then
              echo "Python-3-incompatible code found"
              cat futurize_diffs
              exit 1
            fi

  generate_py27py36_wagon:
    steps:
      - run:
          name: Create Workspace Build directory.
          command: mkdir -p workspace/build
      - run:
          name: Build py27py36 Wagon
          command: |
              git clone https://github.com/cloudify-cosmo/cloudify-wagon-build-containers.git
              docker build -t cloudify-centos-7-wagon-builder cloudify-wagon-build-containers/centos_7_py2py3
              docker run -v ~/project/:/packaging cloudify-centos-7-wagon-builder
      - run:
          name: copy wagon to workspace
          command: cp *.wgn workspace/build/
      - persist_to_workspace:
          root: workspace
          paths:
            - build/*

  generate_rhel_py27py36_wagon:
    steps:
      - run:
          name: Create Workspace Build directory.
          command: mkdir -p workspace/build
      - run:
          name: Build RHEL py27py36 Wagon
          command: |
              git clone https://github.com/cloudify-cosmo/cloudify-wagon-build-containers.git
              docker build -t cloudify-redhat-7-wagon-builder cloudify-wagon-build-containers/redhat_7_py2py3 --build-arg USERNAME="$USERNAME" --build-arg PASSWORD="$PASSWORD"
              docker run -v ~/project/:/packaging cloudify-redhat-7-wagon-builder
      - run:
          name: copy wagon to workspace
          command: cp *.wgn workspace/build/
      - persist_to_workspace:
          root: workspace
          paths:
            - build/*

  build_archive:
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Create Workspace Build directory.
          command: mkdir -p workspace/build
      - run:
          name: Build Bundle
          command: |
            git clone https://github.com/cloudify-incubator/cloudify-ecosystem-test.git
            pip install -e cloudify-ecosystem-test
            python -c 'from ecosystem_cicd_tools import packaging; packaging.build_plugins_bundle_with_workspace()'
      - persist_to_workspace:
          root: workspace
          paths:
            - build/*

  release_plugin:
    steps:
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote --recursive
      - run:
          name: Download pip
          command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
      - run:
          name: Install pip
          command: sudo python get-pip.py
      - run:
          name: Install virtualenv
          command: pip install --user virtualenv
      - run:
          name: Init virtualenv
          command: virtualenv env
      - run:
          name: install tox
          command: pip install --user pygithub pyyaml==3.10
      - run:
          name: upgrade setuptools
          command: pip install --upgrade setuptools
      - run:
          name: install local project
          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip
      - attach_workspace:
          at: workspace
      - run: python .circleci/package_release.py

  create_manager_container_505:
    steps:
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive
      - attach_workspace:
          at: workspace
      - run:
          name: update pip
          command: pip install -U pip===20.3.3
      - run:
          name: install cloudify
          command: |
            pip install -r test-requirements.txt
      - run:
          name: download manager docker image
          command: wget http://repository.cloudifysource.org/cloudify/5.0.5/ga-release/cloudify-docker-manager-5.0.5.tar
      - run:
          name: load docker image
          command: docker load -i cloudify-docker-manager-5.0.5.tar
      - run:
          name: retain space by dumping the tar
          command: rm cloudify-docker-manager-5.0.5.tar
      - run:
          name: show images
          command: docker images
      - run:
          name: start docker container
          command: docker run --name cfy_manager -d --restart unless-stopped -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock --security-opt seccomp:unconfined --cap-add SYS_ADMIN --network host cloudifyplatform/premium-cloudify-manager-aio
      - run:
          name: install local project
          command: pip install git+https://github.com/cloudify-incubator/cloudify-ecosystem-test.git@migrating-aws-to-new-tool

  create_manager_container_py3:
    steps:
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive --remote
      - attach_workspace:
          at: workspace
      - run:
          name: update pip
          command: pip install -U pip===20.3.3
      - run:
          name: install cloudify
          command: |
            pip install -r test-requirements.txt
      - run:
          name: download manager docker image
          command:  wget http://repository.cloudifysource.org/cloudify/5.1.0/.dev1-release/cloudify-manager-aio-docker-5.1.0.dev1.tar
      - run:
          name: load docker image
          command: docker load -i cloudify-manager-aio-docker-5.1.0.dev1.tar
      - run:
          name: retain space by dumping the tar
          command: rm cloudify-manager-aio-docker-5.1.0.dev1.tar
      - run:
          name: show images
          command: docker images
      - run:
          name: start docker container
          command: docker run --name cfy_manager -d --restart unless-stopped -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock --security-opt seccomp:unconfined --cap-add SYS_ADMIN --network host cloudify-manager-aio:latest
      - run:
          name: wait for starter
          command: docker exec -it cfy_manager cfy_manager wait-for-starter
      - run:
          name: install local project
          command: pip install git+https://github.com/cloudify-incubator/cloudify-ecosystem-test.git@migrating-aws-to-new-tool

  prepare_test_manager:
    steps:
      - run: ecosystem-test prepare-test-manager -l $TEST_LICENSE -es gcp_credentials=$gcp_credentials --bundle-path workspace/build/cloudify-plugins-bundle.tgz

  run_virtual_machine_test:
    steps:
      - run: ecosystem-test local-blueprint-test  -b examples/blueprint-examples/virtual-machine/gcp.yaml --test-id=virtual-machine --on-failure=uninstall-force --timeout=1800

  run_gke_test:
    steps:
      - run: ecosystem-test local-blueprint-test  -b examples/blueprint-examples/kubernetes/gcp-gke/blueprint.yaml --test-id=gcp-gke  -i resource_prefix=gcpresource-$CIRCLE_BUILD_NUM --on-failure=uninstall-force --timeout=3000

jobs:

  unittests_py27:
    executor: py27
    steps:
      - checkout
      - run_unittest_py27

  unittests_py36:
    executor: py36
    steps:
      - checkout
      - run_unittest_py36

  py3_compat:
    executor: py27
    steps:
      - checkout
      - check_py3_compat

  wagon:
    executor: wagon_generator
    steps:
      - checkout
      - generate_py27py36_wagon

  rhel_wagon:
    executor: wagon_generator
    steps:
      - checkout
      - generate_rhel_py27py36_wagon

  build_bundle:
    executor: py36
    steps:
      - checkout
      - build_archive

  virtual_machine_integration_tests_505:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - create_manager_container_505
      - prepare_test_manager
      - run_virtual_machine_test

  gke_integration_tests_505:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - create_manager_container_505
      - prepare_test_manager
      - run_gke_test

  virtual_machine_integration_tests_py3:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - create_manager_container_py3
      - prepare_test_manager
      - run_virtual_machine_test

  gke_integration_tests_py3:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - create_manager_container_py3
      - prepare_test_manager
      - run_gke_test

  validate_version:
    executor: py36
    steps:
      - checkout
      - validate_version

  validate_documentation:
    executor: py36
    steps:
      - checkout
      - validate_documentation

  release:
    executor: py36
    steps:
      - checkout
      - release_plugin

workflows:
  version: 2.1
  tests:
    jobs:
      - py3_compat
      - unittests_py27
      - unittests_py36
      - validate_version
      - validate_documentation
      - wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - build_bundle:
          filters:
            branches:
              only: /master/
          requires:
            - wagon
            - rhel_wagon
      - virtual_machine_integration_tests_505:
          requires:
            - build_bundle
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - gke_integration_tests_505:
          requires:
            - build_bundle
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - virtual_machine_integration_tests_py3:
          requires:
            - build_bundle
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - gke_integration_tests_py3:
          requires:
            - build_bundle
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - release:
          filters:
            branches:
              only: /master/
          requires:
            - unittests_py27
            - unittests_py36
            - wagon
            - rhel_wagon
            - virtual_machine_integration_tests_505
            - gke_integration_tests_505
            - virtual_machine_integration_tests_py3
            - gke_integration_tests_py3

  nightly:
    triggers:
    - schedule:
        cron: "0 1 * * *"
        filters:
          branches:
            only:
              - master
    jobs:
      - py3_compat
      - unittests_py27
      - unittests_py36
      - validate_version
      - wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - build_bundle:
          filters:
            branches:
              only: /master/
          requires:
            - wagon
            - rhel_wagon
      - virtual_machine_integration_tests_505:
          requires:
            - build_bundle
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - gke_integration_tests_505:
          requires:
            - build_bundle
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - virtual_machine_integration_tests_py3:
          requires:
            - build_bundle
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - gke_integration_tests_py3:
          requires:
            - build_bundle
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
